<a href="https://colab.research.google.com/github/ambermartin-data-lab/healthfirst-data-analytics-academy-2025-2026/blob/main/Class_assignment_3_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/refs/heads/master/mtcars.csv")

In [3]:
df.head()

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [4]:
df.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [6]:
df = df.rename(columns={"Unnamed: 0": "car"})

In [7]:
df_subset = df[["mpg", "hp", "wt", "cyl"]]

In [11]:
df_subset = df_subset.rename(columns={
    "mpg": "miles_per_gallon",
    "hp": "horsepower",
    "wt": "weight",
    "cyl": "cylinders"
})

In [10]:
df_subset.mean()

miles_per_gallon     20.090625
horsepower          146.687500
weight                3.217250
cylinders             6.187500
dtype: float64

In [12]:
df_subset.describe()

       miles_per_gallon  horsepower     weight  cylinders
count         32.000000   32.000000  32.000000  32.000000
mean          20.090625  146.687500   3.217250   6.187500
std            6.026948   68.562868   0.978457   1.785922
min           10.400000   52.000000   1.513000   4.000000
25%           15.425000   96.500000   2.581250   4.000000
50%           19.200000  123.000000   3.325000   6.000000
75%           22.800000  180.000000   3.610000   8.000000
max           33.900000  335.000000   5.424000   8.000000

In [13]:
df_6cyl = df_subset[df_subset["cylinders"] == 6]

df_6cyl.describe()

       miles_per_gallon  horsepower    weight  cylinders
count          7.000000    7.000000  7.000000        7.0
mean          19.742857  122.285714  3.117143        6.0
std            1.453567   24.260491  0.356346        0.0
min           17.800000  105.000000  2.620000        6.0
25%           18.650000  110.000000  2.822500        6.0
50%           19.700000  110.000000  3.215000        6.0
75%           21.000000  123.000000  3.440000        6.0
max           21.400000  175.000000  3.460000        6.0